services:
  nginx:
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:

      - ./certs:/etc/letsencrypt
      - ./conf:/etc/nginx/conf.d
  bot:
    environment:
      - IS_DOCKER=true
    build: .
    #container_name: bot
    # command: bash -c "cd /app &&alembic upgrade head &&alembic revision --autogenerate && alembic upgrade head && python start_bot.py"
    env_file:
      - .env
    restart: always
    # depends_on:
    #   - db
    #   - redis
    # volumes:
    #   - .:/app
    # networks:
    #   - app-tier
  webhook:
    hostname: stripewebhook
    build:
      context: .
      dockerfile: Dockerfile.webhook
    # container_name: webhook
    env_file:
      - .env
    # ports:
    #   - "8080:8000"
    depends_on:
      - bot
  db:
    image: mysql:8.0.36
    container_name: db
    hostname: mysql
    command: --init-file /data/application/init.sql
    restart: always
    env_file:
      - .env
    volumes:
      - my-db:/var/lib/mysql
      - ./database/init.sql:/data/application/init.sql
    networks:
      - app-tier