services:
  bot:
    container_name: bot
    hostname: bot
    env_file:
      - .env
    #image: example/database
    build:
      context: .
      dockerfile: ./Dockerfile
    # ports:
    #     - '8000:8000'
  postgres:
      container_name: db
      environment:
        POSTGRES_PASSWORD: 7830
        PGDATA: /var/lib/postgresql/data/pgdata
      image: postgres:17
      hostname: pgsql
      restart: always
      env_file:
      - .env
      # set shared memory limit when using docker-compose
      shm_size: 128mb
      # or set shared memory limit when deploy via swarm stack
      volumes:
        - /opt/postgres3:/var/lib/postgresql/data/pgdata

      #  - type: tmpfs
      #    target: /dev/shm
      #    tmpfs:
      #      size: 134217728 # 128*2^20 bytes = 128Mb
  nginx:
    image: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:

      - ./certs:/etc/letsencrypt
      - ./conf:/etc/nginx/conf.d

  webhook:
    hostname: stripewebhook
    build:
      context: .
      dockerfile: Dockerfile.webhook
    container_name: webhook
    env_file:
      - .env
    # ports:
    #   - "8080:8000"
    depends_on:
      - bot