"""вв

Revision ID: 9e542f4b2b8c
Revises: e367b3eeabeb
Create Date: 2025-03-09 18:15:38.657002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e542f4b2b8c'
down_revision: Union[str, None] = 'e367b3eeabeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchases', sa.Column('expires', sa.Date(), nullable=True))
    op.add_column('tariffs', sa.Column('data', sa.Date(), nullable=True))
    op.drop_column('tariffs', 'file_id')
    op.add_column('typoftariffs', sa.Column('how_much_days', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('typoftariffs', 'how_much_days')
    op.add_column('tariffs', sa.Column('file_id', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('tariffs', 'data')
    op.drop_column('purchases', 'expires')
    # ### end Alembic commands ###
